### ISSUE TITLE
Hi, it seems You & I are doing something similar: About fonts, translator…for Unicode.

### ISSUE THREAD

**Issue by MY1L** [Mercury13/unicodia#271]
My English is poor, 所以就用中文了。下列也许对你有用（has a look to develop to you usefully.

----

all Unicode Block Name Chinese translation, even the [roadmaps](https://www.unicode.org/roadmaps/):
https://github.com/MY1L/Unicode/blob/main/Blocks

----

3 fonts (OFL1.1) support ALL CJK Unified Ideographs (Extension A,B,C,D,E,F,G,H), CJK Sym & Kana: [Monu Han*](https://github.com/MY1L/Unicode/releases?q=MonuHani&expanded=true)
https://github.com/MY1L/Unicode/tree/main/Hani （中文）

----

my Original free fonts——

[Ctrl Ctrl](https://github.com/MY1L/Ctrl/releases/tag/Ctr1)— support Control Pictures, Ideographic Description Characters (Unicode 15.1!) & Control Character,Variation Selectors,Format Controls(like Control Pictures)…
![](https://github.com/MY1L/Ctrl/raw/main/res/Ctrl.png)

[Ctrl Kana](https://github.com/MY1L/Ctrl/releases/tag/Kana)— support Kana Extended-B…
![](https://user-images.githubusercontent.com/58043328/219873654-72073f1e-6c9c-4c60-ac24-4ba720b88035.png)

[Ctrl Runr](https://github.com/MY1L/Ctrl/releases/tag/v1-beta.6)— support Runic & [Cirth](https://www.evertype.com/standards/csur/cirth.html)
![](https://github.com/MY1L/Ctrl/raw/main/res/Runr.png)

[Ctrl Math](https://github.com/MY1L/Unicode/releases/tag/NotoUni7)— support Kaktovik Numerals (2023-2-14) 

https://github.com/MY1L/Ctrl

and [Nüshu Serif](https://github.com/MY1L/Nyushu)

----

a better “Last Resort” font (OFL1.1): [Monu Last](https://github.com/MY1L/Unicode/releases?q=Last&expanded=true)
https://github.com/MY1L/Unicode/releases/tag/Last8 (upcoming…)
![MLv8 10~11](https://user-images.githubusercontent.com/58043328/233777937-7140c307-1450-4864-a688-9d0169aeee8a.png)

----

~~one collection font~~ (OFL1.1, without OpenType feature, deprecated)
![](https://user-images.githubusercontent.com/58043328/219955343-65520303-aaaa-46d1-ae9c-6127428f0457.png)

**Comment by Mercury13** [comment]
You… you are so cool! I’m making the most comprehensive character map ever.
If you can translate my Unicodia to Chinese — I’d like to!
Of course, I’m always looking for better fonts.

**Comment by Mercury13** [comment]
@MY1L , where do you take ideograph images from? And which style do you use: Chinese, Japanese etc?

**Comment by Mercury13** [comment]
@MY1L , Which fonts I really lack:
Devanagari: lots of technical issues in Noto
Lanna: sans-serif for one of the nicest scripts in the world?
Oriya: lags behind
Orkhon runes: same
Small kana: need sans-serif here
CJK: collect comprehensive set of characters, scrap obsolete GlyphWiki font at last
Buginese: want serif
Sundanese: lags behind, no historical ligatures
Makasar: need bird style, but not mechanical vectorization
Egyptian hieroglyphs: lag behind
Coptic: need serif

**Comment by Mercury13** [comment]
Your Unicode font lacks any functionality! This is just a set of glyphs ripped from somewhere.
So I need to check thoroughly where every glyph was taken from.

**Comment by Mercury13** [comment]
My UnicodiaSutton is almost glyph-to-glyph copy of Noto SignWriting, and I didn’t even change copyright. But functionality is brand new.

**Comment by Mercury13** [comment]
@MY1L , what’s the source of your kana characters? Have you drawn them for yourself?

**Comment by MY1L** [comment]
> Your Unicode font lacks any functionality!

So I said “**without OpenType feature, deprecated**”, “Noto Unicode” designed to surrogate [unifont](http://www.unifoundry.com/unifont/index.html).

one font cannot display over 65535 glyphs, So I gave up functionality (for SignWriting and others)

> So I need to check thoroughly where every glyph was taken from.

all records here (in Chinese, excessively long)—— 
Before ver5: https://github.com/MY1L/Unicode/tree/main/NotoUnicode
v5→6.9: https://github.com/MY1L/Unicode/releases/tag/NotoUni6
v5.901→7.x: https://github.com/MY1L/Unicode/blob/main/NotoUnicode/NotoUni7.md

as above, some glyphs are My original since 2020: ؝𞁊⏻⏼⏽🜁🜃🜍🜿……design principles are “Notolike”.

**Comment by MY1L** [comment]
all kana Supp(𛀀𛀁), kana Ext-A(𛄈𛄟𛄠𛄡𛄢), kana Ext-B are Original.
![倭](https://github.com/Mercury13/unicodia/assets/58043328/3570ccf7-e0e8-48cc-a3e3-0f66f647512f)

small “Proportional” kana designed with the [コーポレート・ロゴ v
2](https://logotype.jp/corporate-logo-font-dl-old-v2.html)(OFL1.1) in mind. I made it in 2020 Apr.
by the way, コーポレート・ロゴ only Medium Weight & Bold Weight, excludes small kana Ext, so I drawn all “Regular”
![image](https://github.com/Mercury13/unicodia/assets/58043328/4ab0b49e-1a53-4391-b559-e90af35b0514)

**Comment by Mercury13** [comment]
@MY1L So may I take a few to my Unicodia?

**Comment by Mercury13** [comment]
Thank you, trying to graft your Min and small kana. I’ll probably make hiero structure for myself from scratch, IDK.

**Comment by Mercury13** [comment]
@MY1L  Thank you, trying to graft your Min and small kana. I’ll probably make hiero structure for myself from scratch, IDK.

**Comment by MY1L** [comment]
> So may I take a few to my Unicodia?

Yes you can.

I'm late😫, my GitHub account lockouts over the past few months, [because I can't enable two-factor authentication](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/) in Mainland China, it looks like this↓
![image](https://github.com/Mercury13/unicodia/assets/58043328/d2e47960-7825-4682-ba35-c950e3951dfc)

----

### Now I'm working on fonts follow-up Unicode v16+ & ISO 15924
![image](https://github.com/Mercury13/unicodia/assets/58043328/e5101742-c8d7-474f-bac3-d9f993e80045)

**Comment by Mercury13** [comment]
I have taken. I made 2FA (I looked for an app for several days, stopped on 2FAS). There’s a war in Ukraine, and IDK how to make backup ways. It’s possible that I escape somewhere with empty hands → how to restore?
