### ISSUE TITLE
Flag emojis are unsearchable

### ISSUE THREAD

**Issue by curya** [Mercury13/unicodia#311]
Searching for any flag emoji only provides results for the "regional indicator symbol" letters.

Example: Searching for 🇺🇸 only returns 🇺 and 🇸.

**Comment by Mercury13** [comment]
This is both a problem and a feature.
1. Emoji are unsearchable, but how to search them? Could you suggest?
2. This is a feature, split into characters. And 🇺🇸 is actually  🇺+🇸.
![image](https://github.com/Mercury13/unicodia/assets/10164882/35bfaa90-2c56-4c6d-a1c8-a5c40c4171c1)

**Comment by Mercury13** [comment]
P.S. When I deleted characters between U and S, they ligated into USA flag.

**Comment by Mercury13** [comment]
@curya , maybe you have some suggestions?

**Comment by Mercury13** [comment]
@curya You have written “🇺 and 🇸”. When I delete “␣and␣”, I instantly get 🇺🇸.
Right now emoji search is not implemented, and what problems I have:
1. How to tell multi-character emoji from a normal single character.
2. How to return to search list if we moved to wrong place.
3. How to treat “us flag” if I have “flag: United States”

**Comment by Mercury13** [comment]
I instantly get 🇺🇸 in Firefox+W10, it has Twemoji on board. If you have Chromelike+W10, you won’t get, as W10 has no flag emoji, and Chromelikes completely rely on system emoji.

**Comment by curya** [comment]
![image](https://github.com/Mercury13/unicodia/assets/71131343/7bcc43a1-4055-4a86-9fb8-bb1326c89739)
This is what I get when typing 🇺🇸 after deleting " and ".

And like I said, I'm probably the wrong person to ask about how to solve this problem. I'm not a programmer. Maybe you can contact the people at emojipedia and ask how they did it?

**Comment by curya** [comment]
It shouldn't matter what OS I'm on. Unicodia should display the emoji correctly. In this case, the flags.

Pasting the emoji itself is a step in the right direction. But I feel like the program should also return the correct emoji when searching for "us flag" or "uk flag" or whatever. (Not regional indicator letters).

Just a suggestion. Maybe move the emoji search to the Library tab?

**Comment by Mercury13** [comment]
UA, US and so on are actually two codepoints and do not fit straightly into my “break into codepoints” feature. That’s why I’m asking to devise a solution. Right now I’m thinking about data structures that will find finished multi-character emoji inside text, but that’s another thing.

**Comment by Mercury13** [comment]
@curya 
Just by tags you see, I took your request seriously, and thinking what to do and how to help you.
I know that Unicodia has these problems.

**Comment by curya** [comment]
I appreciate it! Unfortunately, I'm not sure I can help you. Maybe there should be a separate "emoji" tab so we can search flags (🇺🇸) and all variations of emojis (like 👱🏻‍♀️)?

**Comment by Mercury13** [comment]
@curya Recently I’ve read a well-known story about Pontiac that started when the owner bought chocolate ice-cream, and refused when he bought vanilla ice-cream. It was hard to translate from owner’s language to engineer’s one. Vanilla ice-cream (default in the USA, thus term “vanilla” for original unmodded software) was in a separate fridge, and buying it was quicker. Because of carburettor deficiencies, the car failed to start. (VAZ owners will come: cover it with a wet rag.)

**Comment by Mercury13** [comment]
![image](https://github.com/Mercury13/unicodia/assets/10164882/b746af39-896d-4001-9f5e-0dc5e4976291)
@curya Is it OK?

**Comment by Mercury13** [comment]
I will not release until Noto runs through all their fonts. And I’ll write more.

**Comment by curya** [comment]
> @curya Recently I’ve read a well-known story about Pontiac that started when the owner bought chocolate ice-cream, and refused when he bought vanilla ice-cream. It was hard to translate from owner’s language to engineer’s one. Vanilla ice-cream (default in the USA, thus term “vanilla” for original unmodded software) was in a separate fridge, and buying it was quicker. Because of carburettor deficiencies, the car failed to start in a specific time range after stopping. (VAZ owners will come: cover it with a wet rag.)

I think something is lost in translation here...



> @curya Is it OK?

Looks good to me. I'll have to test it when the new version is released.

**Comment by Mercury13** [comment]
@curya Google “pontiac vanilla ice cream”
About VAZ (Volga Automobile Plant): to own a car/moped in the USSR, you needed to do most of maintenance for yourself, so Soviet car-owners knew lots of lifehacks.

Noto did nothing today, waiting for monthly release.

**Comment by curya** [comment]
Does this support the other multi-character emojis as well?
👱🏻‍♀️
🧑‍🧑‍🧒
🐦‍🔥
🍋‍🟩

**Comment by Mercury13** [comment]
![image](https://github.com/Mercury13/unicodia/assets/10164882/61c26b8c-770d-485e-a042-c5ec79a9287b)

**Comment by Mercury13** [comment]
Everything is decodable except single-character and VS16.

**Comment by Mercury13** [comment]
@curya One more search rule
![image](https://github.com/Mercury13/unicodia/assets/10164882/367f2df7-0f41-4a5d-bba3-4ab727791808)

**Comment by curya** [comment]
What if I type "ua flag"?

**Comment by Mercury13** [comment]
Right now nothing. I’ll try of course.

**Comment by Mercury13** [comment]
@curya Done
![image](https://github.com/Mercury13/unicodia/assets/10164882/996c7f0f-1b09-4381-9db6-1ecab695b091)

**Comment by Mercury13** [comment]
Words “flag” and “of” are flag-related keywords. “Of” is dubious (the last counts if several), and “flag” is just a keyword.
So “of flag ua” and “ua flag” do the same.
More than 3 words, digits → bad string, no search

**Comment by curya** [comment]
Nice.

Does it also work with "ukraine flag" or "ukraine"?

**Comment by Mercury13** [comment]
@curya Normal emoji search isn’t done yet, mostly because of special words like “person” and “flag”. But test what I made.

**Comment by Mercury13** [comment]
@curya Making an emergency fix right now, I’ll think later about true emoji search.

**Comment by curya** [comment]
It seems to work very well. Thanks for making this work! :)

**Comment by Mercury13** [comment]
@curya @MAZ06
This isn’t exactly your task, but did today…
- You can find a character by its emoji name: e.g. both “savoring” (emoji) and “savouring” (character)

**Comment by Mercury13** [comment]
@curya Did some basic search, but I need backup ASCII characters.

**Comment by Mercury13** [comment]
![image](https://github.com/Mercury13/unicodia/assets/10164882/6c3b8d4f-da45-4f51-a84f-3f582f00cbe6)
Still need backup ASCII characters

**Comment by Mercury13** [comment]
Need to find «Aland»
![image](https://github.com/Mercury13/unicodia/assets/10164882/6d99cebe-46c9-45ff-bb92-2fd89d4fa1f8)

Should be this
![image](https://github.com/Mercury13/unicodia/assets/10164882/c039d07c-e8cd-4cb5-b362-a6397dca5b8a)

**Comment by Mercury13** [comment]
Now works this way
![image](https://github.com/Mercury13/unicodia/assets/10164882/1237e40a-2f84-4c35-b838-4863f4873cf6)
