### ISSUE TITLE
Make it seeable... i have see a Screenshoot, but not here.., so issue= Screenshoot

### ISSUE THREAD

**Issue by blackcrack** [Mercury13/unicodia#321]
Hi,

i come from(walk from) EFB.NU, so a german Freewareboard where listed your Program,
i find Unicode sighn's very helpful and very practical ..
and i have noticed here, there is no screenshoot.... humm, you can naturally speak about and destription in verbal in very rich and round form, but a Picture say more as 1000 word's in one view, like you shure know ;) therefor would really helpful a Screenshoot or a link to a screenshoot Page ... I have fount in KDE/Plasma a Smilyselectore, where is like your program/ your Unicode-Selectore would really helpful in Plasma too, there should you bring in front to be this Proggy wrote in QT (Version?) (if i am right) and bring this in front too, maybe at the Screenshoot Link by side ..
Would nice if i found this nice proggy at Plasma in Linux as extra Proggy as standard addon Program...

1. Nice idea, 2. Nice  and usable Programm ! Mille gracie ! 
and i hope i find it as RPM in Fedora as depencie in Plasma/KDE

(if you make Screenshoots, can you close this comment/issue)

best
blacky

Blackysgate.de

**Comment by kenmcd** [comment]
Look here: https://mercury13.github.io/unicodia/

**Comment by blackcrack** [comment]
hmm.. Установите автоматический переводчик, тогда язык будет определяться и переводиться автоматически с помощью распознавания речи через браузер через PHP или Java ;)
hmm.. bau doch einen automatischen Übersetzer ein, dann wird per spracherkennung über den browser über php oder Java die Sprache Festgestellt und automatisch übersetzt ;)
hmm..Install an automatic translator, then the language will be determined and automatically translated using language recognition via the browser via PHP or Java ;)
