### ISSUE TITLE
"mathematical Fraktur small k" is broken

### ISSUE THREAD

**Issue by curya** [Mercury13/unicodia#323]
As the title says, "mathematical Fraktur small k" is not appearing correctly:
![image](https://github.com/Mercury13/unicodia/assets/71131343/2bda5d64-268e-4486-9810-54164f897cd7)

It should look like this:
![image](https://github.com/Mercury13/unicodia/assets/71131343/ec0963e1-9868-462e-9877-54ff4e6c2dda)

The bold version is also affected:
![image](https://github.com/Mercury13/unicodia/assets/71131343/6fe8342d-ae35-4b35-842a-ed369f99cfcb)
![image](https://github.com/Mercury13/unicodia/assets/71131343/7600c2c0-5d77-48cc-83a0-4f96556bec09)

**Comment by Mercury13** [comment]
@curya Maybe I’ll find a new font for the entire Fraktur math. I use Cambria for now, as title says.

**Comment by curya** [comment]
Why not Noto Math?

**Comment by Mercury13** [comment]
> Why not Noto Math?

Probably too big metrics, IDK.

**Comment by kenmcd** [comment]
This form from Cambria Math is the most widely used.
Not sure why, but it is.
This form is what is in the official Unicode Code Charts.
This form is in STIX Two Math.
This form is in all the TeX Gyre math fonts.
This form is in MathJax Fraktur.
So this may be the expected form.

Minion Math does not have those fraktur characters.
So I guess they would come from another font.
The old Lucida Bright Math symbol fonts do not have those characters.
But the Lucida Blackletter font does have the same form as NotoSans Math.
So Noto Sans Math is the only math font I have found with that form.
Yes, it is more recognizable, but why is the other form used more?
And used in the Unicode Code Charts?

Would be interesting to see what form is used in published books.
I agree the Noto Sans form is more recognizable to non-math people.
But is it what math-people expect?

**Comment by Mercury13** [comment]
Blackletter K is so rare that I probably won’t find anything. Fraktur k actually looks this way, interesting.

**Comment by Mercury13** [comment]
I’m a post-Soviet man familiar with advanced maths. And blackletter K in our country would look somehow simpler.
But we have no Gothic tradition, of course.

**Comment by Mercury13** [comment]
Right now I’ll just write: Some Fraktur letters are barely recognizable. Both Unicode charts and most fonts, including Windows and TeX, are designed this way, though some mathematicians, especially in non-Latin countries, use simpler fonts.
