### ISSUE TITLE
Alt codes

### ISSUE THREAD

**Issue by jobytoss** [Mercury13/unicodia#329]
Hi!
Is there a way to see what is the actual Alt code for the selected symbol?
For example the € symbol is written using "Alt + 0128".
Thank you!
![sshot-2024-03-10- 00-23-29](https://github.com/Mercury13/unicodia/assets/130220534/2079bba7-fc6d-4b6b-bb40-94aa35381fb6)

**Comment by Mercury13** [comment]
Thank you. I really missed Alt code 0128, it’ll be next release.

**Comment by Mercury13** [comment]
Checked the rest, probably okay.

**Comment by jobytoss** [comment]
What I would like is when I select a symbol in the left pane, to see in the right pane what is the actual Alt code for that symbol, like here: https://www.alt-codes.net
Example:
![sshot-2024-03-10- 01-32-23](https://github.com/Mercury13/unicodia/assets/130220534/2a1c340d-f224-42a5-b325-48c6f02a62c2)

P.S. I added Unicodia to the TPFC database, hope it's OK: https://www.portablefreeware.com/index.php?id=3102

**Comment by Mercury13** [comment]
I intentionally missed Alt codes for ASCII, as all printable ASCII characters are accessible from keyboard.
Unicodia IS portable, but you should tweak Unicodia.xml file to keep config next to EXE file.
![image](https://github.com/Mercury13/unicodia/assets/10164882/04a11609-4db3-482e-bf5a-6a6f71ab8671)

**Comment by jobytoss** [comment]
Oh, I understand now, there are Alt codes displayed, but only for non-ASCII symbols.

Regarding the portability yes, I mentioned replacing the string portable="0" with portable="1" in the Unicodia.xml file.

Thank you!

Issue closed.

**Comment by Mercury13** [comment]
Found more recent bugs, so euro in 2.3.9 now.
