### ISSUE TITLE
Searching flags by country name

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#337]
Hi. I just recently started using Unicodia. Really great program!

I wanted to ask if it would be possible to search for flag emojis by typing the country name. Right now it's only possible to search for them by using the country code. "US" works. But "United States" or "America" do not.

Thanks!

**Comment by Mercury13** [comment]
Thank you. I didn’t implement searching for emoji for now because of false alarms. I didn’t invent a good algorithm.

**Comment by Mercury13** [comment]
@MAZ06
How it’s handled in Blocks.
Some words are considered “special”, e.g. “letter”. If match is in this special word, the result is pessimized.
I have not found a way to program whether this word is true or special.

**Comment by Mercury13** [comment]
@MAZ06
As emoji descriptions contain umlauts and typographic apostrophes, need approximate search.
These are challenges.
