### ISSUE TITLE
Compilation isue

### ISSUE THREAD

**Issue by NSP-0123456** [Mercury13/unicodia#339]
Cannot compile with QT 6.6.3 oss,
isues with QIcon not included
isues with QString

// Compile on win64 with QT install and included mingw64 
@set WORKAROUND=
@set QTDIR=d:\Qt\6.6.3\mingw_64\
@set MINGW=d:\Qt\Tools\mingw1120_64\bin\

**Comment by Mercury13** [comment]
Thx. I did not test the newest Qt because of lack of workarounds for W7, and much slower startup (it’s really important for small utility like Unicodia).

**Comment by Mercury13** [comment]
You see my commit, cherry-pick it to your branch.
setButtonText is deprecated, I did nothing with it for now.
