### ISSUE TITLE
Unicode History - Feature Request

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#344]
Just an idea. I thought it would be nice to have a Unicode History tab so you can see exactly which glyphs were added in each version.

So like you could click on "Unicode 16.0" and see all the new additions.

**Comment by Mercury13** [comment]
I thought about it. Will use existing search engine.

**Comment by Mercury13** [comment]
@MAZ06
Got usability trouble.
Sometimes there are big blocks (e.g. Egyptian A in U16), and they will spam out the entire search.

**Comment by MAZ06** [comment]
@Mercury13 I thought of it as being it's own separate tab. That way no search is necessary. Everything would already be pre-sorted.

So something like... on the left we see the blocks. On the right we can selecte "Unicode 15.1" or "Unicode 16.0", etc.

**Comment by Mercury13** [comment]
Search is universal. You can add other categories to search through.
Got an idea, but will be a bit hard to implement.

**Comment by Mercury13** [comment]
@MAZ06 
![image](https://github.com/Mercury13/unicodia/assets/10164882/24f24a54-7527-4fa5-bd2b-423b80d77972)
Does not work completely, but I’m trying.
That’s 15.0

**Comment by MAZ06** [comment]
How do I search for a Unicode version?

**Comment by Mercury13** [comment]
Click anywhere on version (character info, block info, emoji info). Or all versions are in Terms.

Then search icon.

![image](https://github.com/Mercury13/unicodia/assets/10164882/7da53680-b23c-4f70-9d4e-14b65a6a5e42)

**Comment by Mercury13** [comment]
Search icons will be everywhere. You click search icon, and Unicodia implements some query.

**Comment by MAZ06** [comment]
Thanks. That works nicely. But it is a little tedious to get to...

I'm still in favor of dedicated tab.
