### ISSUE TITLE
Link to emoji Library from Blocks - Feature Request

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#345]
If I go to the Library, I can see an emoji and get linked to the specific block. For example, 😀 has a link to 1F600 which when clicked takes me back to the Blocks tab with that emoji. That's great, but the opposite is not possible.

For example, if I search for "superhero" in the Blocks tab, there should be a link to "superhero" in the Library tab so I can see all the skin colors. This should apply to all emojis that have similar variations (ie skin color, hair color, etc).

And actually, it may be easier and more useful to just put all the variations in the emoji description itself in the Blocks tab. No need to make an extra step back to the Library.

**Comment by Mercury13** [comment]
@MAZ06
I can make a straightforward link, but there are a few things.
1. How should it look like?
2. In Qt I use there are problems with QTextBrowser, at least in the version I use: cannot display HiDPI images. I wanted to show all emoji using this character, but How should they look like? The bar in Library is just a workaround: I made a custom widget that can display everything I want.

**Comment by MAZ06** [comment]
Windows 7 has had no support for 4 years now. I think it's ok to upgrade.

**Comment by MAZ06** [comment]
How should it look? I think the same as it is now. Have the default yellow-skin emoji exactly the way it is now but then underneath it show all the variations.

**Comment by Mercury13** [comment]
In late 2021, when I switched Qt 6.1 → 6.2, W7 users complained.
And I still need some tests whether they have fixed this.

**Comment by Mercury13** [comment]
Checked changelogs, did not fix, still they’re saying about QImage which is purely bitmap.
Custom drawing? Cannot find a hook I can hang on.

**Comment by Mercury13** [comment]
@MAZ06  KATS in Duployan shorthand is also a workaround: if I cannot put an SVG, maybe I’ll draw it as a big character?

**Comment by Mercury13** [comment]
@MAZ06 Working, you’ll see how it…

**Comment by Mercury13** [comment]
@MAZ06 
![image](https://github.com/Mercury13/unicodia/assets/10164882/06949056-e60d-4b72-8f63-7bd15302ee77)
Does not work for now, but here it is

**Comment by MAZ06** [comment]
How are multiple skin colors handled?

**Comment by Mercury13** [comment]
@MAZ06 There will be no skin colours, this is just a link to Library.

**Comment by Mercury13** [comment]
@MAZ06 Released, check what I kolkhozed.

**Comment by MAZ06** [comment]
@Mercury13 Very nice! Thank you! I may have a few more ideas...
