### ISSUE TITLE
Tofu Statistics?

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#350]
Somehow I accidentally opened this menu:
![image](https://github.com/Mercury13/unicodia/assets/165231781/5208de89-a342-4f96-b8c4-6293f16ee7ef)

How did I do this?

**Comment by MAZ06** [comment]
Oh I see that it's in the About tab. But I never touched that. Is there some sort of hotkey?

**Comment by Mercury13** [comment]
Ctrl+T

**Comment by Mercury13** [comment]
Was introduced long before that link.

**Comment by Mercury13** [comment]
@MAZ06 Replaced with Ctrl+Shift+T.
