### ISSUE TITLE
compilation issue "AutoBuilder\unibase.cpp"

### ISSUE THREAD

**Issue by NSP-0123456** [Mercury13/unicodia#351]
I've switched to new gcc and get compilation issue on file "AutoBuilder\unibase.cpp" due to a constinit with uninitialized structure.

```
constinit ucd::Numeric NO_NUMERIC {
      |                            ^~~~~~~~~~
../AutoBuilder/unibase.cpp:35:5: error: temporary of non-literal type 'std::string' {aka 'std::__cxx11::basic_string<char>'} in a constant expression
   35 |     };
```
The simpliest way to compile was to change to
`const ucd::Numeric NO_NUMERIC = {`
_'Probably not the best but compile even with newest QT 6.7_

**Comment by Mercury13** [comment]
Done, someday I used string_view, but switched to string.
