### ISSUE TITLE
Make installer (setup) for Windows

### ISSUE THREAD

**Issue by xmha97** [Mercury13/unicodia#355]
Hi, please make an installer (setup) for the Windows.

**Comment by nataliakeniganti** [comment]
![bandicam 2024-11-01 11-46-32-232](https://github.com/user-attachments/assets/81ebc153-ed1d-4deb-b7d6-07009680c26c)

**Comment by Mercury13** [comment]
I know. That’s the contents of archive. Next version will contain installer or 7z, to your choice.
