### ISSUE TITLE
[Feature Request] Red hearts

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#369]
This is a small quality-of-life request. When adding something to Favorites, the heart stays empty. It would nice if the heart filled in completely red to signify that it has already been added to Favorites.

**Comment by Mercury13** [comment]
Interesting, I‘ll think how to do that. Qt probably has some functionality for this. Blackouts became bad, and waking up to electricity “killed” me for almost a week.
I‘m slowly moving to laptop, but a UPS for internet bought 1.5 yrs ago proved poor: it overcharges a battery, and it lasts for 4h now, and does not hold cycle “5h electricity — 4h blackout”. Chinese powerbank of 16 cells?
Working on emoji search now.

**Comment by Mercury13** [comment]
Current problem is: emoji are adorned with typography, and need some approximate search.

**Comment by Mercury13** [comment]
And if you‘ve seen my “warm lamp coldstarter”. Desktop UPS cannot coldstart my computer, and I managed to start it with incandescent lamp as a resistor. “Warm tube sound” is an audiophiles’ meme, and “(vacuum) tube” and “lamp” are the same word in Russian.

**Comment by Mercury13** [comment]
![image](https://github.com/Mercury13/unicodia/assets/10164882/e745d8ef-8c10-4c75-a785-226adccda14e)
Is it cool? Or we need some transparency?

**Comment by Mercury13** [comment]
UPD: transparency bad! Let it be solid-filled.
