### ISSUE TITLE
Searching multiple flags

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#371]
When searching for multiple flags at the same time, the results will only show the first one.

Example: 🇵🇷🇨🇺🇪🇸

![image](https://github.com/user-attachments/assets/9bb75533-d285-40e3-a19a-5b62c16c8d63)

**Comment by Mercury13** [comment]
Big funk, blackout now, I’ll give it a try in the evening — if I stay alive.

**Comment by Mercury13** [comment]
Currently I’m drawing serif Ol Onal. If I stay alive, I’ll make it in a week.

**Comment by Mercury13** [comment]
![изображение](https://github.com/user-attachments/assets/d8d6ca21-63d5-4c04-89bf-0406fea8dcbc)

**Comment by Mercury13** [comment]
@MAZ06, test! I released.
