### ISSUE TITLE
Musical sizes and positions

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#372]
I've noticed that there are many music glyphs that are very different sizes and in strange positions.

![image](https://github.com/user-attachments/assets/7915bb4c-cb4c-44e5-9343-bc0de5a3548b)

U+1D132 is really small. U+1D130 and U+1D131 are positioned very low. There are several more music glyphs that have these issues.

**Comment by Mercury13** [comment]
Actually so small in Noto Music. And so small in Unicode chart. Noto Music tends to use actual character sizes — look at G clef, it’s really big, I was forced to use a fixup font!
And Noto Music is probably SMuFL compatible but IDK. SMuFL is a side-standard for musical fonts.
![image](https://github.com/user-attachments/assets/0c29c256-750f-48b2-9aa9-275a4a16fcf7)
Close?

**Comment by Mercury13** [comment]
SMuFL says they should be equal in size. I’m not a musician.

**Comment by MAZ06** [comment]
I think all notation should be equal in size. I would trust SMuFL on this.

**Comment by Mercury13** [comment]
Then ask Noto Music. I would use Bravura as a new font, but it has no 25CC, and has no new characters of Persian music.

**Comment by MAZ06** [comment]
Can you link to where SMuFL says they should be equal in size? I'll include it in my issue for Noto Music.

**Comment by MAZ06** [comment]
Just found a strange issue...
Unicodia:
![image](https://github.com/user-attachments/assets/baf8afd1-81b9-4e19-8481-411a02884321)
Noto Music:
![image](https://github.com/user-attachments/assets/0527e4a8-ea87-4d25-8965-865e9a51dc61)

**Comment by Mercury13** [comment]
@MAZ06
Here are standard accidentals: flat, sharp etc.,
https://w3c.github.io/smufl/latest/tables/standard-accidentals-12-edo.html

Here are other accidentals: 4-sharp and 4-flat
https://w3c.github.io/smufl/latest/tables/other-accidentals.html

**Comment by MAZ06** [comment]
Thanks.

This is also an issue. Too tall for the box.
![image](https://github.com/user-attachments/assets/d3c02dc6-07fb-4739-b7e4-330b02dabdd6)

**Comment by Mercury13** [comment]
About 1/128th note — I won’t fix. Too small of issue.
I’ll really enlarge Byzantine music and fit it into smaller box.

**Comment by Mercury13** [comment]
@MAZ06 Let’s make a complete list for ME:
1. Take five notes from Noto Music and put them to Misc chars.
2. Add fixup glyphs for micro-sharp/flat,
3. Enlarge a bit Byzantine and squeeze into small window (already OK).

Do not:
1. So anything for 1/128th note.

OK?

**Comment by MAZ06** [comment]
What do you mean "Misc. chars"?

**Comment by Mercury13** [comment]
@MAZ06 Actually seven: 2669 to 266F.

**Comment by Mercury13** [comment]
2. Decided to check what to do. The character is so rare that I’ll better refuse to change it. Even researchers did not see it in the wild. :(
