### ISSUE TITLE
Regional indicators "To Library" broken

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#373]
Regional indicators have "To Library" text, but clicking it does nothing.

![image](https://github.com/user-attachments/assets/df13393b-307a-4494-8e95-f448a489bbc4)

**Comment by MAZ06** [comment]
Maybe they should be in the Library since they're technically emojis...

**Comment by Mercury13** [comment]
Sticking them to Emoji is an interesting task.

**Comment by Mercury13** [comment]
Emoji are downloaded and compiled automatically, so need a special rule: find Components, add Regional indicators…
