### ISSUE TITLE
U+FDFC misrender

### ISSUE THREAD

**Issue by MAZ06** [Mercury13/unicodia#375]
The rial sign (U+FDFC) misrenders in Unicodia. But I think it may also be an issue with the font. I may have to report it to Noto Arabic as well.

Unicodia:
![image](https://github.com/user-attachments/assets/58c7760f-3eac-4386-82d6-d9cc6bf1c6d1)

Noto:
![image](https://github.com/user-attachments/assets/e4f7c224-3092-4a03-bf7b-8cf2f8ee30d4)

**Comment by MAZ06** [comment]
So apparently the Unicode chart displays U+FDFC as separate letters. The stylized version is not in there. It's up to you if you want to include it in Unicodia or not.

**Comment by Mercury13** [comment]
I use Scheherazade here.
Close as not planned?

**Comment by MAZ06** [comment]
Noto would produce the same result actually unless you literally copy and paste the actual symbol.

Also, I'm still confused why Unicodia is using Scheherazade instead of Noto...

**Comment by Mercury13** [comment]
Because Scheherazade adopts new characters more quickly, and is just more complex Naskh.

**Comment by MAZ06** [comment]
Why not use Noto for everything so everything is the same style? And then only use other fonts when you absolutely need to? For example, when new characters come out.

**Comment by Mercury13** [comment]
Arabic and European cannot be the same style.

**Comment by MAZ06** [comment]
Maybe I used the wrong words. I guess I meant to say the same *font family*.

**Comment by Mercury13** [comment]
![image](https://github.com/user-attachments/assets/931f9181-01ed-4f80-9a35-909feb9a9ae5)
