### ISSUE TITLE
Fix eject button

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#391]

**Comment by Mercury13** [comment]
![Uploading image.png…]()

**Comment by Mercury13** [comment]
What’s wrong?

**Comment by Mercury13** [comment]
![image](https://github.com/user-attachments/assets/19e1323b-3cde-4ad1-b9df-e5a515b770db)
What’s wrong?

**Comment by Mercury13** [comment]
It’s a VS16 emoji — it’s shown as text+emoji, unless emoji looks bad in small size or some strange P1 block (I’ve fixed timer, so all Misc Tech are going to be within general rule, wait for 2.8.6)

**Comment by Mercury13** [comment]
Misrender — at least show me that misrender…

**Comment by nataliakeniganti** [comment]
Does this support the other multi-character emojis as well?
🇨🇶
🧑‍⚕️
😮‍💨
🧑‍🚀

**Comment by Mercury13** [comment]
What is “this” and what is “support”? Unicodia has them in Library, but using custom pictures instead of some font.

**Comment by nataliakeniganti** [comment]
Closes 1 hour
