### ISSUE TITLE
Contrast more emojis

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#395]
Remake contrast emoji.
🌬 U+1F32C Wind blowing face
🦷 U+1F9B7 Tooth
🪄 U+1FA84 Magic wand
🪅 U+1FA85 Pinata
🪿 U+1FABF Goose

**Comment by Mercury13** [comment]
I use Google Noto, and dislike bad contrast myself, complained at it to Noto

Wind blowing face: IDK how
Tooth: not really a cool artist
Magic wand: already increased contrast somehow, need more but how?
Pinata: IDK
Goose: it’s really cool, won’t change!

**Comment by nataliakeniganti** [comment]
> I use Google Noto, and dislike bad contrast myself, complained at it to Noto
> 
> Wind blowing face: IDK how
> Tooth: not really a cool artist
> Magic wand: already increased contrast somehow, need more but how?
> Pinata: IDK
> Goose: it’s really cool, won’t change!

Finish commit contrast emoji

**Comment by Mercury13** [comment]
I increased contrast for myself:
Tornado
Flags containing white, per-case
Placard
Jar
White dove, swan
