### ISSUE TITLE
Add tulu block

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#398]

**Comment by Mercury13** [comment]
If it were easy…
I tried to talk to author of MODERN Tulu font, but he did not respond.
Here’s a block of ANCIENT Tulu, and there’s a consensus to not unify ancient and modern. The sample font for ANCIENT Tulu is commercial.
Even a gag of 80 glyphs is >week of work. Well, I did gags for Nandinagari and Dives until true working fonts came.
WORKING Tulu is ≈200…300 glyphs.
(Working Gurung w/o Windows’ rules is >100 glyphs too, but most of those glyphs are auto-created.)

**Comment by Mercury13** [comment]
I’m too lazy to give to Noto my Gurung and Ol Onal; Todhri HAS been given.

**Comment by Mercury13** [comment]
Just look at two blocks of tofu. A really big Indic script, and 4000 Egyptian hieros. Understand why they are tofu?

**Comment by nataliakeniganti** [comment]
Support the unicode characters

𑎀
𑎁
𑎂	
𑎃
𑎄
𑎅
𑎆
𑎇
𑎈
𑎉

**Comment by nataliakeniganti** [comment]
Update `Fonts/NotoSansEgyptianHieroglyphs-Regular.otf`.

**Comment by Mercury13** [comment]
Do I need to support four characters 11392+113D0+113A1+113B9?
11392 Tulu-Tigalari letter Ka
113D0 Tulu-Tigalari conjoiner
113A1 Tulu-Tigalari letter Ta
113B9 Tulu-Tigalari vowel sign I
Together they are a common syllable KTI.
That’s a working font for Indic script.
Noto Devanagari contains ONE THOUSAND glyphs and >200 rules. Tulu won’t be that big (most Deva’s characters are metric substitutes — wide I, wider I, really wide I), but still Indic scripts are HARD. I can make a gag, and I did this for Diak/Nand until real fonts came, but too weak for a working font. The luck of Gukh was absence of those syllables, and the only thing I needed was to emulate reordering rules (IDK whether they are present now) and hang anusvara.

**Comment by Mercury13** [comment]
A bad feature of OpenType: it relies on system’s reordering rules.

**Comment by nataliakeniganti** [comment]
> A bad feature of OpenType: it relies on system’s reordering rules.

Use fontlab 7

**Comment by Mercury13** [comment]
For Tulu it probably won’t be that hard, but we have what we have, as said one of our politicians (Kravchuk?)

**Comment by Mercury13** [comment]
Do you need a gag (a set of glyphs that gags those tofu) or a working font? As we say in Odesa, that’s two big differences.

**Comment by Mercury13** [comment]
About OpenType:
As you see, Makasar has one table of two rules, just dot doubling.
![image](https://github.com/user-attachments/assets/eb7f8409-e53f-40e3-a00a-fa8eebdb9313)
Vowel E is just a spacing glyph, won’t show. But everything works somehow!
![image](https://github.com/user-attachments/assets/9e826053-6f86-40f4-8afc-98ed7d5c67f9)
Who puts E before consonant?
Tables present in OpenType engines!
More, you don’t need to draw anything in 11938 Diak O, those tables will automatically make it from 11935 and 11930! And gracefully put 11935 before.
Those rules for Gukh were absent when I tested for the last time, and in Noto Lanna they are emulated too.

**Comment by nataliakeniganti** [comment]
Add Missing Funky Glyphs 4000 Egyptian hieros!!!

**Comment by Mercury13** [comment]
I found ≈2900 with proper license at JSesh. But because of FontForge deficiencies and lack of formalization auto-conversion is a bad deal, I broke teeth.

**Comment by nataliakeniganti** [comment]
Add Funky Tulu Glyphs Source: https://commons.wikimedia.org/wiki/Category:SVG_letters_in_Tulu_script

[Tulu script letter ಅ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%85.svg)354 × 354; 2 KB
 

[Tulu script letter ಆ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%86.svg)100 × 100; 2 KB
 

[Tulu script letter ಇ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%87.svg)100 × 100; 2 KB
 

[Tulu script letter ಈ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%88.svg)150 × 100; 2 KB
 

[Tulu script letter ಉ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%89.svg)100 × 100; 2 KB
 

[Tulu script letter ಊ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%8A.svg)100 × 150; 3 KB
 

[Tulu script letter ಋ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%8B.svg)100 × 100; 2 KB
 

[Tulu script letter ಋಊ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%8B%E0%B2%8A.svg)100 × 100; 3 KB
 

[Tulu script letter ಎ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%8E.svg)150 × 100; 2 KB
 

[Tulu script letter ಏ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%8F.svg)150 × 100; 2 KB
 

[Tulu script letter ಔ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%94.svg)100 × 100; 2 KB
 

[Tulu script letter ಕ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%95.svg)100 × 100; 2 KB
 

[Tulu script letter ಖ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%96.svg)100 × 100; 2 KB
 

[Tulu script letter ಗ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%97.svg)100 × 100; 2 KB
 

[Tulu script letter ಘ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%98.svg)100 × 100; 39 KB
 

[Tulu script letter ಙ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%99.svg)100 × 100; 2 KB
 

[Tulu script letter ಚ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9A.svg)100 × 100; 41 KB
 

[Tulu script letter ಛ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9B.svg)100 × 100; 67 KB
 

[Tulu script letter ಜ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9C.svg)100 × 100; 63 KB
 

[Tulu script letter ಝ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9D.svg)100 × 100; 2 KB
 

[Tulu script letter ಞ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9E.svg)100 × 100; 2 KB
 

[Tulu script letter ಟ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%9F.svg)100 × 100; 2 KB
 

[Tulu script letter ಠ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A0.svg)100 × 100; 2 KB
 

[Tulu script letter ಡ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A1.svg)100 × 100; 341 KB
 

[Tulu script letter ಢ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A2.svg)100 × 100; 2 KB
 

[Tulu script letter ಣ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A3.svg)100 × 100; 2 KB
 

[Tulu script letter ತ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A4.svg)100 × 100; 2 KB
 

[Tulu script letter ಥ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A5.svg)100 × 100; 2 KB
 

[Tulu script letter ದ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A6.svg)100 × 100; 2 KB
 

[Tulu script letter ಧ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A7.svg)100 × 100; 2 KB
 

[Tulu script letter ನ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%A8.svg)100 × 100; 2 KB
 

[Tulu script letter ಪ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%AA.svg)100 × 100; 2 KB
 

[Tulu script letter ಫ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%AB.svg)100 × 100; 2 KB
 

[Tulu script letter ಬ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%AC.svg)100 × 100; 2 KB
 

[Tulu script letter ಮ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%AE.svg)100 × 100; 2 KB
 

[Tulu script letter ಯ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%AF.svg)100 × 100; 2 KB
 

[Tulu script letter ರ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B0.svg)100 × 100; 2 KB
 

[Tulu script letter ಲ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B2.svg)100 × 100; 2 KB
 

[Tulu script letter ಳ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B3.svg)100 × 100; 2 KB
 

[Tulu script letter ವ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B5.svg)100 × 100; 2 KB
 

[Tulu script letter ಷ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B7.svg)100 × 100; 2 KB
 

[Tulu script letter ಸ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B8.svg)100 × 100; 2 KB
 

[Tulu script letter ಹ.svg](https://commons.wikimedia.org/wiki/File:Tulu_script_letter_%E0%B2%B9.svg)100 × 100; 2 KB

**Comment by Mercury13** [comment]
Is this Tulu modern or ancient? (Probably modern) Some letters repeat, and I still don’t see 80 glyphs.
Again, will it be gag or working font? For Indic scripts that’s “two big differences”.
For example: Devanagari K क + virama ◌् + R र + I ◌ि = KRI क्रि, a common syllable.

**Comment by Mercury13** [comment]
Ancient and modern Tulu were not unified due to the way virama works: dead script usually have virtual virama to convey author’s spelling, and in modern ones visible virama and conjoiner are the same character to simplify everyday typing.

**Comment by Mercury13** [comment]
I REALLY want to make Brahmi from scratch, but I just see the amount of work…

**Comment by Mercury13** [comment]
Another reason: modern Tulu was revived just a few years ago, and there’s no de facto standard to encode.

**Comment by nataliakeniganti** [comment]
> Another reason: modern Tulu was revived just a few years ago, and there’s no de facto standard to encode. As I said multiple times, Indic font ⪢⪢⪢ a collection of glyphs, unlike Latin and my native Cyrillic: it’s not just a letter shape, but methods of syllable composition.

is done commit

**Comment by Mercury13** [comment]
![image](https://github.com/user-attachments/assets/44c4bce1-e458-416f-b057-592db447c473)
If no yet data in Windows, I won’t be able to make even half-working font.

**Comment by Mercury13** [comment]
In Gurung — no glyph reordering yet. At least in Firefox.
![image](https://github.com/user-attachments/assets/601f17a6-a2ea-4f5f-948d-7af3b25c28c3)

**Comment by Mercury13** [comment]
![image](https://github.com/user-attachments/assets/4153ccc9-4968-4171-be32-33309a6cf411)
What does it mean? Reordering tables aren’t yet ready. It’s possible to do it in Graphite etc, but my Unicodia does not support Graphite. It’s possible to emulate somehow with OpenType, but probably hard.

**Comment by Mercury13** [comment]
Desired result: 113C2 ■◌, 113C8 ■◌▲.

**Comment by Mercury13** [comment]
More interesting tasks, and completable even now.
1. Dark skin.
2. Composition of CJK ideographs (got a base).

**Comment by nataliakeniganti** [comment]
> ![image](https://private-user-images.githubusercontent.com/10164882/380499680-4153ccc9-4968-4171-be32-33309a6cf411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzUzMjMsIm5iZiI6MTczMDAzNTAyMywicGF0aCI6Ii8xMDE2NDg4Mi8zODA0OTk2ODAtNDE1M2NjYzktNDk2OC00MTcxLWJlMzItMzMzMDlhNmNmNDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4N2JkMmJjNjYwMWI2YzQxMTEzOGU1NWEzNTZjZDIwMjFkYjk1ZmMyZjI1MmVkMWQ0MmRkMTE2ZGRjODE4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x0P-6NHr4Np7wSluMKtaYde9ATb7vJUaU0kH0GebHOw) What does it mean? Reordering tables aren’t yet ready. It’s possible to do it in Graphite etc, but my Unicodia does not support Graphite. It’s possible to emulate somehow with OpenType, but probably hard.

Showing glitches

**Comment by Mercury13** [comment]
> Showing glitches
No, they are hastily-drawn glyphs to test specific OpenType feature we’re waiting for.

**Comment by Mercury13** [comment]
Well, Natalia. If you can use vector editor — maybe you can draw them FOR YOURSELF?
I promise to create a half-working font if you can really draw normal glyphs by drawings of that Indian lady rather than images of whatever.
I promise to leave credits.

DIMENSIONS: W×1000 pixels. Width doesn’t really matter, bearings are corrected in font editor.
IMPORTANT POINTS. Top of letters like H and X is at Y=86, but you can set it greater, 100 or 150.
Baseline is at Y=800.
STROKE: Probably 50 to 80 pixels is OK. Maybe 60 or 65, the font is stroke-heavy.
OPTICAL COMPENSATION. Round things should be ≈15px below baseline, and 15px above topline.
OTHER: Leave SVG as human-editable as possible. Have you seen “23” and “23a”? The latter is a conversion to format edible by FontForge. I’ll do all conversions for myself.
Drawings outside canvas should be far enough to be easily deleted, and close enough to be easily noticed.
Guides and bitmaps may be placed wherever you want, FontForge ignores them.

Make 3 or 4 letters in a pull request, BUT NOT INDEPENDENT VOWELS — better some consonants.

**Comment by Mercury13** [comment]
COMPOUND GLYPHS: If the glyph is a combination of two smaller glyphs, DO NOT draw it at all, everything will be done in font editor.

**Comment by Mercury13** [comment]
FILL AND STROKE. Do not use BOTH fill and stroke in the same OBJECT. Either fill, if you are drawing the object with fill, or stroke, if you are drawing with stroke.

**Comment by nataliakeniganti** [comment]
Add missing tulu funky glyphs

**Comment by nataliakeniganti** [comment]
Add label new unicode

**Comment by Mercury13** [comment]
> Add missing tulu funky glyphs

Indic font is MORE MORE than a collection of glyphs.

**Comment by Mercury13** [comment]
:) IDK what to do with repha: syllable r + K + Oo should be reordered to: leftO, K, r, rightO

**Comment by Mercury13** [comment]
With normal syllables I even invented a workaround: K+conj+T+Oo → leftO-K, conj, T, rightO.
Or if I make special letters (later): leftO-K, subT, rightO.
AFAIK, exchange rK → Kr is impossible in OpenType, and workaround ligatures leftO-K-r… IDK.

**Comment by nataliakeniganti** [comment]
> I made a big argument with Simon Cozens about 11A3A Zanb repha: it always had a dotted circle on the right, and he did not know how to get rid. Because lots of work was done in OpenType engine, without any way to change it on font level.
> Sometime that repha was a gag glyph in my Funky, but I managed to find a workaround: there’s a flag “no OpenType’ing” here in Qt, render sequence of glyphs without any additional processing.

New unicodia funky glyphs

**Comment by Mercury13** [comment]
Sorry, lady, Indic font is not just glyphs. Maybe I’ll make a gag, but I really want to make at least a half-working font.

**Comment by nataliakeniganti** [comment]
> Just look at two blocks of tofu. A really big Indic script, and 4000 Egyptian hieros. Understand why they are tofu?

Fixes on commit #398

**Comment by Mercury13** [comment]
Sorry, lady, you do not understand what commit is. This is not an issue. Commit is in Git and has a hex code as number.

**Comment by nataliakeniganti** [comment]
Add in 2025

**Comment by Mercury13** [comment]
Again, those SVGs are bad by license. Probably poor and they are actually PD, but won’t test.

**Comment by Mercury13** [comment]
![image](https://github.com/user-attachments/assets/7af3ba81-ceb6-4acd-8c9d-1078ffacc8d9)
Testing for now, but even gagging Tutg is really hard. Not saying about working font: Indic font ≠ collection of glyphs!

**Comment by Mercury13** [comment]
Probably I’ll make another font with separate metrics: Tutg heavily relies on low letters.

**Comment by nataliakeniganti** [comment]
Add more letters

**Comment by nataliakeniganti** [comment]
Fix the vowels it worked 𑏅𑏉

**Comment by Mercury13** [comment]
@nataliakeniganti, Started work, but even half-working font is HAARD.
![image](https://github.com/user-attachments/assets/3b388595-0641-4d51-b399-561f73679e95)

**Comment by nataliakeniganti** [comment]
Add glyphs full version?

**Comment by Mercury13** [comment]
Even if I make 10 glyphs/day (unlikely), the simplest gag font is 9 to 10 days. Half-working (simplest syllables and viramas) — ≈20 days. Fully working (complex syllables) — >month.
HAAAAAAAAAAARD.

**Comment by Mercury13** [comment]
Found some font!
Still seventeen tofu…
Probably in a few days I’ll have a gag font.
![image](https://github.com/user-attachments/assets/9e164c54-f335-4487-a660-7223b574777a)

**Comment by Mercury13** [comment]
Eight tofu so far…

**Comment by nataliakeniganti** [comment]
Add Missing Not tofu glyphs
```
U+11387
U+11389
U+11390
U+11391
U+1139A
U+113B7
U+113BD
U+113BE
U+113BF
U+113C0
U+113CF
U+113D3
U+113D4
U+113D5
U+113D7
U+113E1
U+113E2
```

**Comment by Mercury13** [comment]
Why, Natalia, are you spamming me?
You see, I started work?

**Comment by nataliakeniganti** [comment]
i finished

**Comment by Mercury13** [comment]
@nataliakeniganti I started to actually support Tulu syllables, and not even 10% finished.
![image](https://github.com/user-attachments/assets/7ccecbc0-4fc3-4f8d-8259-f105d32a98aa)

**Comment by Mercury13** [comment]
My aim is to support all attested (vocalic R/Rr — somehow unless actually attested) and all two-consonant with all vowels.
