### ISSUE TITLE
Low contrast wind face

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#404]
![bandicam 2024-11-01 19-43-18-802](https://github.com/user-attachments/assets/315da001-8ada-477f-a6f8-869ad67e3021)
![emoji_u1f32c](https://github.com/user-attachments/assets/b5922b68-f881-4ce8-9571-e537c8874d3c)

**Comment by Mercury13** [comment]
Again, very basic work.

**Comment by nataliakeniganti** [comment]
commit is working 10 minutes

**Comment by Mercury13** [comment]
Noto…
![image](https://github.com/user-attachments/assets/28dc6809-3679-4761-aabf-9f2d160a92b1)
