### ISSUE TITLE
Remake: Nail polish

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#406]
Hands using clipping paths.
![bandicam 2024-11-02 18-18-22-838](https://github.com/user-attachments/assets/22d05c8a-fefe-4931-88b0-6de69a9d5035)

**Comment by Mercury13** [comment]
False alarm, no clip path (was not updated in U16 release)

**Comment by Mercury13** [comment]
Natalia, do you understand why I’m afraid of clipping paths? They are just unsupported by Qt’s SVG engine.

**Comment by Mercury13** [comment]
And I don’t see artifacts related to clipping paths.

**Comment by Mercury13** [comment]
Previous nail polish USED TO clip.
