### ISSUE TITLE
U+3026 misrender

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#407]
The hangzhou numeral six (U+3026) misrenders in Unicodia. But I think it may also be an issue with the font. I may have to report it to Noto Japanese as well.

Unicodia:
![bandicam 2024-11-05 06-31-10-220](https://github.com/user-attachments/assets/af80612c-975f-433a-83b8-7186c1da0bd2)

Noto:
![bandicam 2024-11-05 06-30-17-068](https://github.com/user-attachments/assets/8630685f-dbbf-45dc-9489-721cb2f894c1)

**Comment by Mercury13** [comment]
Updated glyph of U16. Done intentionally in 2.8.6.

**Comment by Mercury13** [comment]
Why 2.8.6? Updated BabelStone Han, checked #332, changed font chain
