### ISSUE TITLE
All tofu in palymere and nabataean

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#413]

**Comment by Mercury13** [comment]
I really need your help here.
This is a known transient bug, and depending on loading order, the fonts may or may not load.
After writing my own checker whether the character is supported, I did not see it even a single time.

**Comment by Mercury13** [comment]
…after writing in 2.8

**Comment by Mercury13** [comment]
What EXACTLY have you done?

**Comment by Mercury13** [comment]
In upcoming version probability of this bug will be really lower.
