### ISSUE TITLE
upd Afghanistan

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#417]
![bandicam 2024-11-21 19-06-44-649](https://github.com/user-attachments/assets/72d3ef21-f3ff-40df-8ed6-7e2580bbc524)

**Comment by Mercury13** [comment]
You mean Taliban?

**Other images are possible!** Current (2024) government, Taliban, is recognized almost nowhere. Their flag is white with black shahada, Muslim motto. Meanwhile vendors use the old flag abandoned in 2021.

**Comment by nataliakeniganti** [comment]
> You mean Taliban?
> 
> **Other images are possible!** Current (2024) government, Taliban, is recognized almost nowhere. Their flag is white with black shahada, Muslim motto. Meanwhile vendors use the old flag abandoned in 2021.

![image](https://github.com/user-attachments/assets/0ae97b85-1f54-4749-997f-c99f3cb82fd7)
is done
