### ISSUE TITLE
What is "trigger-stamp"?

### ISSUE THREAD

**Issue by coolvitto** [Mercury13/unicodia#423]
In English locale.xml it is trigger-stamp="2022060"
but what is the value in Japanese?
trigger-stamp="???????"

**Comment by Mercury13** [comment]
Date-based, e.g. 2024110
What does it do?
Language appeared → got triggerStamp greater than every existing stamp, triggering switching to new language if it’s set in OS
Language greatly improved (e.q. auto-translated → manually proofread) → increase once more to let people try improved translation once again.

**Comment by coolvitto** [comment]
Thank you.
I'm currently creating the Japanese language file and will post it once it's completed.

**Comment by Mercury13** [comment]
Do you use UTranslator and *.utran?

**Comment by Mercury13** [comment]
They are designed to keep track of changing strings.

**Comment by coolvitto** [comment]
I am editing en.uorig with UTranslator.

**Comment by Mercury13** [comment]
NO: you should start a new project, translation of *.uorig.

**Comment by Mercury13** [comment]
OK, send me both original *.uorig (what you actually translated) and new *.uorig, and I’ll try to merge them to a single translation.

**Comment by coolvitto** [comment]
I am editing en.uorig and creating ja.uorig.

**Comment by Mercury13** [comment]
UTranslator’s architecture is single uorig and multiple utran’s.
Sometimes it’s better to translate from another language, it’s done using “reference translations”. References AREN’T kept track of. References MAY form loops.
OK, translate for now, but save the en.uorig you actually translated. I’ll write “merge two originals into translation”.

**Comment by coolvitto** [comment]
OK, I'll post it again after I've finished it.

**Comment by Mercury13** [comment]
BUT SAVE the en.uorig you actually translated!!! Thank you.

**Comment by Mercury13** [comment]
I’ll probably close this ticket, as we are talking in #424.
