### ISSUE TITLE
Add English translation

### ISSUE THREAD

**Issue by tommai4881** [Mercury13/unicodia#89]

**Comment by Mercury13** [comment]
Thanks, after 1.0.
Currently working on verifying texts.
You see, after some moment Russian aux. texts turned to English, so I’m really going to internationalize it.
Difficult, I should invent some globalization chain.
Challenges: do not know tools very much, lots of samples in exotic scripts, long texts that consist of several paragraph and undergo both style and fact editing.

**Comment by Mercury13** [comment]
And another challenge: glossaries, some sorted alphabetically, some are not.

**Comment by Mercury13** [comment]
From among two tasks, emoji library and globalization, I currently chose globalization. Sitting in evacuation, have desktop computer and some sort of internet.

**Comment by Mercury13** [comment]
Hope in two weeks Russian original will be hosted with a new translation tool. Need both original editing and more wiki commands.

**Comment by Mercury13** [comment]
@tommai4881 I’m working to host Russian in separate language resource.

**Comment by Mercury13** [comment]
@tommai4881 Currently I’m working on export to simplest ever type of resource, INI.

**Comment by Mercury13** [comment]
@tommai4881 Still working on L10n…

**Comment by Mercury13** [comment]
@tommai4881 Unicodia’s translation architecture is ALMOST ready (no custom wiki templates). Next stop is infrastructure.

**Comment by Mercury13** [comment]
@tommai4881 Less than 150 strings remain, it’s 1 week if I keep pace. Get ready, guy!

**Comment by Mercury13** [comment]
@tommai4881 Translation done, I just need to remember the choice.
